#!/usr/bin/python3
import json
import subprocess
import time
import sys
import os

DELAY_SECONDS = 3

def load_message(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()

def load_numbers(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def send_sms(device, number, message):
    try:
        result = subprocess.run(
            [
                "kdeconnect-cli",
                "-n", device,
                "--destination", number,
                "--send-sms", message
            ],
            check=True,
            capture_output=True,
            text=True
        )

        print(f"Sent to {number}")
        print("stdout:", result.stdout)
        print("stderr:", result.stderr)

    except subprocess.CalledProcessError as e:
        print(f"Failed to send to {number}")
        print("returncode:", e.returncode)
        print("stdout:", e.stdout)
        print("stderr:", e.stderr)

def main():
    print(sys.argv)
    if len(sys.argv)!=4:
        print("usage: sendsms device messagefile activistlist")
        sys.exit(-1)
    device = sys.argv[1]
    message = load_message(sys.argv[2])
    activistList = sys.argv[3]
    activists = load_numbers(activistList)['records']
    print(activists)

    for record in activists:
        number = record.get("sms", "").strip()
        name = record.get('Hogyan nevezhetünk?',"<no name>").strip()
        print(f"""{name}: {number}""")

        if not number:
            continue  # skip empty sms field

        send_sms(device,number, message)
        time.sleep(DELAY_SECONDS)

if __name__ == "__main__":
    main()
